#!/bin/sh
# Bars and scripts
~/.config/polybar/launch.sh &
~/.config/bspwm/floating-desktop &

# pidof clight || clight --lat=26.83 --lon=80.92 &
xrdb ~/.Xresources

# Normal cursor
xsetroot -cursor_name left_ptr &

# Capslock mapped to escape
xmodmap -e 'clear Lock' #ensures you're not stuck in CAPS on mode
xmodmap -e 'keycode 0x42=Escape' #remaps the keyboard so CAPS LOCK=ESC
